djangojokes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('jokes/', include('jokes.urls')),
    path('', include('pages.urls')),
]

jobs/urls.py
from django.urls import path

from .views import JobAppView, JobAppThanksView

app_name = 'jobs'
urlpatterns = [
    path('job-app/', JobAppView.as_view(), name='app'),
    path('job-app/thanks/', JobAppThanksView.as_view(), name='thanks'),
]

jokes/urls.py
from django.urls import path

from .views import (
    JokeCreateView, JokeDeleteView, JokeDetailView, JokeListView,
    JokeUpdateView
)

app_name = 'jokes'
urlpatterns = [
    path('joke/<slug>/update/', JokeUpdateView.as_view(), name='update'),
    path('joke/<slug>/delete/', JokeDeleteView.as_view(), name='delete'),
    path('joke/create/', JokeCreateView.as_view(), name='create'),
    path('joke/<slug>/', JokeDetailView.as_view(), name='detail'),
    path('', JokeListView.as_view(), name='list'),
]

jokes/models.py
from django.db import models
from django.urls import reverse

from common.utils.text import unique_slug

class Category(models.Model):
    category = models.CharField(max_length=50)
    slug = models.SlugField(
        max_length=50, unique=True, null=False, editable=False
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('jokes:category', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            value = str(self)
            self.slug = unique_slug(value, type(self))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.category

class Joke(models.Model):
    question = models.TextField(max_length=200)
    answer = models.TextField(max_length=100, blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True)
    tags = models.ManyToManyField('Tag', blank=True)
    slug = models.SlugField(
        max_length=50, unique=True, null=True, editable=False
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('jokes:detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            value = str(self)
            self.slug = unique_slug(value, type(self))

        super().save(*args, **kwargs)

    def __str__(self):
        return self.question
    
class Tag(models.Model):
    tag = models.CharField(max_length=50)
    slug = models.SlugField(
        max_length=50, unique=True, null=False, editable=False
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('jokes:tag', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            value = str(self)
            self.slug = unique_slug(value, type(self))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.tag
class Meta:
    ordering = ['tag']

jokes/forms.py
from django.forms import ModelForm, Textarea

from .models import Joke

class JokeForm(ModelForm):
    class Meta:
        model = Joke
        fields = ['question', 'answer', 'category', 'tags']
        widgets = {
            'question': Textarea(
                attrs={'cols': 80, 'rows': 3, 'autofocus': True}
            ),
            'answer': Textarea(
                attrs={'cols': 80, 'rows': 2, 'placeholder': 'Make it funny!'}
            )
        }
        help_texts = {
            'question': 'No dirty jokes please.',
            'tags': 'Use Ctrl-click to select multiple tags.'
        }

jokes/views.py
from django.urls import reverse_lazy

from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView
)

from .models import Joke
from .forms import JokeForm

        
class JokeCreateView(CreateView):
  model = Joke
  form_class = JokeForm

class JokeUpdateView(UpdateView):
  model = Joke
  form_class = JokeForm


class JokeDeleteView(DeleteView):
    model = Joke
    success_url = reverse_lazy('jokes:list')


class JokeDetailView(DetailView):
    model = Joke


class JokeListView(ListView):
    model = Joke

templates/jokes/joke_confirm_delete.html
{% extends "_base.html" %}

{% block title %}Delete Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <form method="post">
      {% csrf_token %}
      <p><strong>Are you sure you want to delete this joke?</strong></p>
      <p>{{ joke.question }}</p>
      <button class="btn btn-success form-control">Confirm</button>
    </form>
  </div>
{% endblock %}

templates/jokes/joke_detail.html
{% extends "_base.html" %}

{% block title %}Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <div class="card-header">{{ joke.question }}</div>
    <div class="card-body text-primary">
      <h5 class="card-title">{{ joke.answer }}</h5>
    </div>
    <div class="card-footer">
      <div class="border-bottom border-faded pb-2">
        <strong>Category:</strong> {{ joke.category }}<br>
        {% for tag in joke.tags.all %}
          <span class="badge rounded-pill bg-secondary">{{ tag }}</span>
        {% endfor %}
      </div>
      <div class="border-bottom border-faded m-2 pb-2">
        <a href="{% url 'jokes:update' joke.slug %}"
          class="btn btn-info btn-sm me-2">Update</a>
        <a href="{% url 'jokes:delete' joke.slug %}"
          class="btn btn-danger btn-sm me-2">Delete</a>
      </div>
      <small class="text-muted">
        Created on: {{ joke.created }}
        Last updated: {{ joke.updated }}
      </small>
    </div>
  </div>
{% endblock %}

templates/jokes/joke_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add/Update Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 p-3"
    style="max-width: 30rem">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success float-end">Submit</button>
      </form>
  </div>
{% endblock %}

templates/jokes/joke_list.html
{% extends "_base.html" %}

{% block title %}Jokes{% endblock %}
{% block main %}
  <a class="btn btn-success btn-sm float-end" href="{% url 'jokes:create' %}">
    + New Joke
  </a>
  <h2>Jokes</h2>
  <ul class="list-group list-group-flush mb-3">
    <div class="table-responsive">
    <table class="table table-striped" style="min-width: 500px">
      <thead>
        <tr>
          <th>Joke</th><th>Category</th><th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for joke in joke_list %}
          <tr>
            <td>
              <a href="{{ joke.get_absolute_url }}">{{ joke.question }}</a>
            </td>
            <td>
              {{ joke.category.category }}<br>
              {% for tag in joke.tags.all %}
                <span class="badge rounded-pill bg-secondary">
                  {{ tag.tag }}
                </span>
              {% endfor %}
            </td>
            <td>
              <a href="{% url 'jokes:update' joke.slug %}">
                <i class="fas fa-pencil-alt"></i>
              </a>
              <a href="{% url 'jokes:delete' joke.slug %}">
                <i class="far fa-trash-alt"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </ul>
{% endblock %}